# Generated by Django 5.1.6 on 2025-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="book_covers/", verbose_name="Обложка"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
